export const GET_PRODUCTS = 'GET_PRODUCTS'
export const BUY_PRODUCT = 'BUY_PRODUCT'
export const ADD_MONEY = 'ADD_MONEY'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_LOADING = 'SET_LOADING'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'